<?php

namespace App\Models\Enums;

enum TypeLookup: int
{
    case STATUS_USER = 1; // ESTATUS DEL USUARIO
    case SERVICES_LIST = 2; // SERVICIOS (REUNIÓN, CHOFER, AUTO)
    case STATUS_REQUEST = 3; // ESTATUS DE SOLICITUD (NUEVA, CANCELADA, EN REVISIÓN, ETC)
    case LEVEL_MEETING = 4; // TIPO DE REUNIÓN (ADMINISTRATIVA O DIRECTIVA)
    case TYPE_SNACK = 5; // (BEBIDA, SNACK, BOCADILLO)
    case STATUS_ROOM = 6; // (ACTIVA, BAJA, MANTENIMIENTO)
}
